# Generated by Django 5.1.4 on 2024-12-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_item_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3-figma-hubfile-images-production.figma.com/hub/file/carousel/img/c03d315e1938db5a050bd6edd265cdcb5787dd24', max_length=500),
        ),
    ]
